name: Update Chart of Running Activities

on:
  workflow_dispatch:   # allow manual trigger
  schedule:
    - cron: "0 21 * * *"   # every day at 09:00 pm UTC

permissions:
  contents: write           # needed for gh-pages deployment

jobs:
  update-chart:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      # 4. Restore Garmin token files from secrets ($HOME refers to the home in the runner)
      - name: Restore Garmin token files
        run: |
          mkdir -p $HOME/.garth
          echo "${{ secrets.GARTH_OAUTH1 }}" | base64 -d > $HOME/.garth/oauth1_token.json 
          echo "${{ secrets.GARTH_OAUTH2 }}" | base64 -d > $HOME/.garth/oauth2_token.json

      # 5. Install dependencies and the project
      - name: Install packaage and dependencies
        run: poetry install --no-interaction

      # 6. Execute the chart plotting (use Console entry point)
      - name: Run Python script
        run: poetry run update-chart
      
      # 7. Deploy Github Pages from branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site   # deploy from repo folder site/
          destination_dir: .    # put it in root of gh-pages branch
          keep_files: false     # replace old version
          force_orphan: true
