name: Update Chart of Running Activities

on:
  workflow_dispatch:   # allow manual trigger
  schedule:
    - cron: "0 9 * * *"   # every day at 09:00 UTC

jobs:
  update-chart:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      # 4. Restore Garmin token files from secrets ($HOME refers to the home in the runner)
      - name: Restore Garmin token files
        run: |
          mkdir -p $HOME/.garth
          echo "${{ secrets.GARTH_OAUTH1 }}" > $HOME/.garth/oauth1_token.json 
          echo "${{ secrets.GARTH_OAUTH2 }}" > $HOME/.garth/oauth2_token.json

      # 4. Install dependencies and the project
      - name: Install packaage and dependencies
        run: poetry install --no-interaction

      # 5. Execute the chart plotting (use Console entry point)
      - name: Run Python script
        run: poetry run update-chart
